version: '3.5'
networks:
  lan:
    driver: bridge
services:
  docker-mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3308:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - lan
  docker-server:
    image: spring-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - lan
    depends_on:
      - docker-mysql
    ports:
      - '8091:8091'
