version: '3.5'
services:
  mysql:
    image: mysql:8
    restart: always
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_DB: teste
  server:
    image: spring-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=testuser
      - DATABASE_NAME=teste
      - DATABASE_PORT=5432
